### PR TITLE
add paging feature via skip query param

### PR DESCRIPTION
**Pull request by lpmi-13**
Added in a skip query param with the intention of allowing people to get the second/third/fourth/etc 10 (or however many) sentences. Seems to be working on my local tests, though admittedly I have no formal tests written to prove that my user tests are correct. Happy to work on that if it's a condition of getting accepted into the codebase, though assuming I would need a lot more help than I did with this feature.

Very happy to discuss any changes that need doing, though already did a check for tab/space formatting, so at least that should pass code review this time! lurz

### CODE REVIEW

**Comment by richdouglasevans** [comment]
Looks good Adam, nice and straightforward :+1:

**Comment by lpmi-13** [comment]
ah yes, I had a feeling that the tests would need to be modified (and we're definitely shipping tests in version 0.0.2!!!). It looks like they just need to be amended with the skip parameter in all expected requests, as well as added in as bogus and non-bogus attempted queries (eg, skip=2, skip=0, skip=Tosh, skip=-6534).

So I'll go ahead and add that in and we should be ready to rock! Thanks again for the major help on this.

**Comment by lpmi-13** [comment]
alright, added in the test coverage stuff, and even double checked for no tabs!! Some of the old space-delete-space may have snuck in there, but it shouldn't affect our heat signature enough for the Romulans to detect.

**Comment by richdouglasevans** [comment]
:+1: merge away homeslice!

**Pull request merged**
